[alias]
reset = "run --bin dev -- reset"
setup = "run --bin dev -- setup"
'run:clean' = "run --bin dev -- clean"

[env]
HOME = { value='/Users/levirogalla/Projects/lib/cli-project-manager/test_root', force=true }
RUST_BACKTRACE='1'
RUST_LOG='debug'