name: Main Branch Release

on:
  push:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  create-release:
    name: Create Release on Main
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this to allow pushing tags
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -1 | sed 's/.*= "//' | sed 's/".*//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
      - name: Create Tag
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

          # Create the tag
          git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"

          # Push using the PAT explicitly in the URL
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git v${{ steps.get_version.outputs.version }}